version: '3.8'
services:
  application:
      build:  
        context: .
        dockerfile: Dockerfile
      container_name: hobby-shop-api
      ports:
        - "8080:8080" 
      depends_on:
        - db 
      networks:
        - api-network

  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: hobby-shop
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - api-network
  
networks:
  api-network:
    driver: bridge